b:
ft -g file://sheets/sheets.c
ft -g file://sheets/sheetc.c
ft -g file://sheets/sheets.h
ft -g file://sdk/string.c
ft -g file://sdk/string.h
ft -g file://sdk/long.c

cc string
era string.c

cc long
era long.c

cc sheets
era sheets.c
cc sheetc
era sheetc.c
era string.h
era sheets.h
clink sheets sheetc string long
era c:sheets.*
a:pip c:sheets.com=sheets.com
era sheets.*
era sheetc.*
era string.*
era long.*
mcpdone sheets
